parameters:
  add:to-host-file:
    hosts:
      - api.saa.local
      - cdn.saa.local
      - breengine-db.saa.local
      - breengine-db.saa.local
      - callsys.saa.local
      - dashboard.kube.saa.systems1
      - dashboard.util.saa.systems
      - dashboard.test.saa.systems
      - dashboard.saa.local
      - email.saa.local
      - extranet-db.saa.local
      - extranet.saa.local
      - webmodule-account.saa.local
      - webmodule-adresinformatie.saa.local
      - webmodule-agent.saa.local
      - webmodule-anva.saa.local
      - webmodule-anvadata.saa.local
      - webmodule-bedrijfsgegevens.saa.local
      - webmodule-breengine.saa.local
      - webmodule-brerule.saa.local
      - webmodule-btbpakket.saa.local
      - webmodule-data-rotation.saa.local
      - webmodule-documenten.saa.local
      - webmodule-downloads.saa.local
      - webmodule-eventstorage.saa.local
      - webmodule-factuur.saa.local
      - webmodule-fish.saa.local
      - webmodule-flow.saa.local
      - webmodule-fraude.saa.local
      - webmodule-nieuweverzekering.saa.local
      - webmodule-menu-hub.saa.local
      - webmodule-pdf.saa.local
      - webmodule-polis.saa.local
      - webmodule-polisvoorwaarden.saa.local
      - webmodule-polis-naar-offerte.saa.local
      - webmodule-postcodegegevens.saa.local
      - webmodule-product.saa.local
      - webmodule-premiebox.saa.local
      - webmodule-relatie.saa.local
      - webmodule-relatiegegevens.saa.local
      - webmodule-schadegegevens.saa.local
      - webmodule-ubo.saa.local
      - webmodule-users.saa.local
      - webmodule-premieverhoging.saa.local
      - webmodule-provisie.saa.local
      - webmodule-voertuiggegevens.saa.local
      - webmodule-vpi.saa.local
      - webportal.saa.local
      - webservices.saa.local
